### ISSUE TITLE
Breaks date parsing in DateTime.new

### ISSUE THREAD

**Issue by zerodogg** [alabamenhu/DateTimeTimezones#2] opened 2020-10-17 15:20 UTC
Getting really strange results from DateTime.new when DateTime::Timezones is loaded:

```sh
[0 zerodogg@mal ~]+$ raku -e 'say DateTime.new("2020-10-01T00:00:00Z")'
2020-10-01T00:00:00Z
[0 zerodogg@mal ~]+$ raku -MDateTime::Timezones -e 'say DateTime.new("2020-10-01T00:00:00Z")'
3920-11-01T00:00:00Z
```

**Comment by zerodogg** [comment] 2020-10-17 17:24
It also occurs when using literal parameters if those are built from non-int types:

```
[0 zerodogg@mal ~]+$ raku -e 'my ($year,$month,$day) = "2020-01-01".split("-"); say DateTime.new(:$year, :$month, :$day, hour => 0, minutes => 0);'
2020-01-01T00:00:00Z
[0 zerodogg@mal ~]+$ raku -MDateTime::Timezones -e 'my ($year,$month,$day) = "2020-01-01".split("-"); say DateTime.new(:$year, :$month, :$day, hour => 0, minutes => 0);'
This type cannot unbox to a native integer: P6opaque, Str
  in method <anon> at /var/home/zerodogg/.raku/sources/3B675F5F3A9B8F11C18AE4B193F9F53345002C31 (DateTime::Timezones) line 119
  in block <unit> at -e line 1
[1 zerodogg@mal ~]+$ raku -MDateTime::Timezones -e 'my ($year,$month,$day) = "2020-01-01".split("-").map: { .Int }; say DateTime.new(:$year, :$month, :$day, hour => 0, mintues => 0);'
2020-01-01T00:00:00Z
```

**Comment by alabamenhu** [comment] 2020-10-17 18:07
> Getting really strange results from DateTime.new when DateTime::Timezones is loaded:
> 
> ```shell
> [0 zerodogg@mal ~]+$ raku -e 'say DateTime.new("2020-10-01T00:00:00Z")'
> 2020-10-01T00:00:00Z
> [0 zerodogg@mal ~]+$ raku -MDateTime::Timezones -e 'say DateTime.new("2020-10-01T00:00:00Z")'
> 3920-11-01T00:00:00Z
> ```

Confirmed.  The standard C struct I model to pass through to one of the time calculators takes the year as an offset from 1900 and the month with a 0-index, and I was passing the times through without accounting for it.  This error would have occurred with a few different construction types, but I've pushed a fix for it.

**Comment by alabamenhu** [comment] 2020-10-17 18:20
> It also occurs when using literal parameters if those are built from non-int types:
> 
> ```
> [0 zerodogg@mal ~]+$ raku -e 'my ($year,$month,$day) = "2020-01-01".split("-"); say DateTime.new(:$year, :$month, :$day, hour => 0, minutes => 0);'
> 2020-01-01T00:00:00Z
> [0 zerodogg@mal ~]+$ raku -MDateTime::Timezones -e 'my ($year,$month,$day) = "2020-01-01".split("-"); say DateTime.new(:$year, :$month, :$day, hour => 0, minutes => 0);'
> This type cannot unbox to a native integer: P6opaque, Str
>   in method <anon> at /var/home/zerodogg/.raku/sources/3B675F5F3A9B8F11C18AE4B193F9F53345002C31 (DateTime::Timezones) line 119
>   in block <unit> at -e line 1
> [1 zerodogg@mal ~]+$ raku -MDateTime::Timezones -e 'my ($year,$month,$day) = "2020-01-01".split("-").map: { .Int }; say DateTime.new(:$year, :$month, :$day, hour => 0, mintues => 0);'
> 2020-01-01T00:00:00Z
> ```

The unboxing occurs because I used native ints for speed, but I wasn't allowing for coercing from Str.  This has now been fixed (maybe not the most elegant one but it works for now).

**Closed as completed by alabamenhu** 2020-10-17 18:20 UTC
Labels: bug
